import type {NextPage} from 'next'
import Head from 'next/head'
import Landing from "../components/Landing";
import MainPage from "../components/Main";
import {GlobalStyles} from "../style/GlobalStyle";
import {Global} from "@emotion/react";

const Home: NextPage = () => {
   return (
     <>
        <Head>
           <title>Yelio</title>
           <meta name="description" content="Generated by create next app"/>
           <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Global styles={GlobalStyles}/>
        <Landing/>
        <MainPage/>
     </>
   );
}

export default Home