import type {NextPage} from 'next'
import Head from 'next/head'
import {GlobalStyles} from "../style/GlobalStyle";
import {Global} from "@emotion/react";
import Main from "../components/Main"
import Landing from "../components/Landing"
const Home: NextPage = () => {
   return (
     <>
        <Head>
           <title>Yelio</title>
           <meta name="description" content="Generated by create next app"/>
           <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Global styles={GlobalStyles}/>
        <Main/>
        <Landing/>
     </>
   );
}

export default Home